resources:
- sas-admin-content-loader/
- sas-analytics-events/
- sas-analytics-execution/
- sas-analytics-gateway/
- sas-analytics-resources/
- sas-annotations/
- sas-app-registry/
- sas-arke/
- sas-audit/
- sas-authorization/
- sas-backup-job/
- sas-batch/
- sas-cas-control/
- sas-cas-operator/
- sas-catalog-services/
- sas-certframe/
- sas-code-debugger/
- sas-code-debugger-app/
- sas-collaboration/
- sas-commonfiles/
- sas-compute/
- sas-configuration/
- sas-connect/
- sas-connect-spawner/
- sas-consul-server/
- sas-content/
- sas-credentials/
- sas-crunchy5-postgres-operator/
- sas-data-agent-server-colocated/
- sas-data-agent-services/
- sas-data-explorer-app/
- sas-data-flows/
- sas-data-mining-project-resources/
- sas-data-mining-results/
- sas-data-mining-risk-models/
- sas-data-quality-services/
- sas-data-server-operator/
- sas-data-sources/
- sas-decision-manager-app/
- sas-decisions-framework/
- sas-decisions-runtime-builder/
- sas-deployment-data/
- sas-device-management/
- sas-drive-app/
- sas-environment-manager-app/
- sas-file-store/
- sas-files/
- sas-formats/
- sas-gen-ai-gateway/
- sas-geography/
- sas-graph-builder-app/
- sas-graph-templates/
- sas-identities/
- sas-import-9/
- sas-import-data-loader/
- sas-information-catalog-app/
- sas-insights/
- sas-inventory-collector/
- sas-job-execution/
- sas-job-execution-app/
- sas-job-flow-scheduling/
- sas-k8s-common/
- sas-landing-app/
- sas-launcher/
- sas-lineage-app/
- sas-list-data/
- sas-localization/
- sas-logon-app/
- sas-microanalytic-score/
- sas-migration-manager/
- sas-ml-pipeline-automation/
- sas-model-builder-job/
- sas-model-manager/
- sas-model-manager-app/
- sas-model-publish/
- sas-model-studio-app/
- sas-natural-language-generation/
- sas-office-addin-app/
- sas-opendistro-operator/
- sas-preferences/
- sas-prepull/
- sas-process-exporter/
- sas-programming-environment/
- sas-pyconfig/
- sas-quality-knowledge-base/
- sas-rabbitmq-server/
- sas-readiness/
- sas-redis-server/
- sas-report-alerts/
- sas-report-distribution/
- sas-report-execution/
- sas-report-renderers/
- sas-report-services-group/
- sas-restore-job/
- sas-risk-cirrus-app/
- sas-risk-cirrus-builder/
- sas-risk-cirrus-core/
- sas-risk-cirrus-objects/
- sas-risk-cirrus-rcc/
- sas-risk-cirrus-rm/
- sas-risk-data/
- sas-risk-modeling-app/
- sas-risk-modeling-core/
- sas-scheduler/
- sas-score-definitions/
- sas-score-execution/
- sas-search/
- sas-studio/
- sas-studio-app/
- sas-studio-development/
- sas-studio-steps/
- sas-subject-contacts/
- sas-text-analytics-data/
- sas-text-analytics-taxonomies/
- sas-theme-designer-app/
- sas-transfer/
- sas-treatment-definitions/
- sas-visual-analytics/
- sas-visual-analytics-app/
- sas-web-assets/
- sas-webhooks/
- sas-workflow-engine/
- sas-workflow-history/
- sas-workflow-manager-app/
- sas-workload-orchestrator/

generators:
- configmaps.yaml