apiVersion: builtin
kind: SecretGenerator
metadata:
  name: sas-consul-config
behavior: merge
literals:
  - INGRESS_HOST=SCO-PE-SAS-PRD.intanis-cloud.net
files:
  - SITEDEFAULT_CONF=site-config/sitedefault.yaml
