---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-v1-ingress-sas-config-reconciler-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: add
    path: /spec/tls
    value: [{hosts: [$(INGRESS_HOST), '*.$(INGRESS_HOST)'], secretName: sas-ingress-certificate}]
target:
  version: v1
  kind: Ingress
  name: sas-config-reconciler
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-v1-ingress-sas-configuration-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: add
    path: /spec/tls
    value: [{hosts: [$(INGRESS_HOST), '*.$(INGRESS_HOST)'], secretName: sas-ingress-certificate}]
target:
  version: v1
  kind: Ingress
  name: sas-configuration
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-v1-ingress-sas-feature-flags-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: add
    path: /spec/tls
    value: [{hosts: [$(INGRESS_HOST), '*.$(INGRESS_HOST)'], secretName: sas-ingress-certificate}]
target:
  version: v1
  kind: Ingress
  name: sas-feature-flags
