resources:
- components/sas-analytics-events/
- components/sas-analytics-execution/
- components/sas-analytics-gateway/
- components/sas-analytics-resources/
- components/sas-annotations/
- components/sas-app-registry/
- components/sas-audit/
- components/sas-authorization/
- components/sas-batch/
- components/sas-cas-control/
- components/sas-catalog-services/
- components/sas-code-debugger/
- components/sas-code-debugger-app/
- components/sas-collaboration/
- components/sas-compute/
- components/sas-configuration/
- components/sas-connect/
- components/sas-content/
- components/sas-credentials/
- components/sas-data-agent-server-colocated/
- components/sas-data-agent-services/
- components/sas-data-explorer-app/
- components/sas-data-flows/
- components/sas-data-mining-project-resources/
- components/sas-data-mining-results/
- components/sas-data-mining-risk-models/
- components/sas-data-quality-services/
- components/sas-data-sources/
- components/sas-decision-manager-app/
- components/sas-decisions-framework/
- components/sas-decisions-runtime-builder/
- components/sas-deployment-data/
- components/sas-device-management/
- components/sas-drive-app/
- components/sas-environment-manager-app/
- components/sas-file-store/
- components/sas-files/
- components/sas-formats/
- components/sas-gen-ai-gateway/
- components/sas-geography/
- components/sas-graph-builder-app/
- components/sas-graph-templates/
- components/sas-identities/
- components/sas-import-9/
- components/sas-information-catalog-app/
- components/sas-insights/
- components/sas-job-execution/
- components/sas-job-execution-app/
- components/sas-job-flow-scheduling/
- components/sas-landing-app/
- components/sas-launcher/
- components/sas-lineage-app/
- components/sas-list-data/
- components/sas-localization/
- components/sas-logon-app/
- components/sas-microanalytic-score/
- components/sas-migration-manager/
- components/sas-ml-pipeline-automation/
- components/sas-model-manager/
- components/sas-model-manager-app/
- components/sas-model-publish/
- components/sas-model-studio-app/
- components/sas-natural-language-generation/
- components/sas-office-addin-app/
- components/sas-preferences/
- components/sas-report-alerts/
- components/sas-report-distribution/
- components/sas-report-execution/
- components/sas-report-renderers/
- components/sas-report-services-group/
- components/sas-risk-cirrus-app/
- components/sas-risk-cirrus-builder/
- components/sas-risk-cirrus-core/
- components/sas-risk-cirrus-objects/
- components/sas-risk-data/
- components/sas-risk-modeling-app/
- components/sas-risk-modeling-core/
- components/sas-scheduler/
- components/sas-score-definitions/
- components/sas-score-execution/
- components/sas-search/
- components/sas-studio/
- components/sas-studio-app/
- components/sas-studio-development/
- components/sas-subject-contacts/
- components/sas-text-analytics-data/
- components/sas-text-analytics-taxonomies/
- components/sas-theme-designer-app/
- components/sas-transfer/
- components/sas-treatment-definitions/
- components/sas-visual-analytics/
- components/sas-visual-analytics-app/
- components/sas-web-assets/
- components/sas-webhooks/
- components/sas-workflow-engine/
- components/sas-workflow-history/
- components/sas-workflow-manager-app/
- components/sas-workload-orchestrator/
generators:
- configmaps.yaml
vars:
- name: INGRESS_HOST
  objref:
    kind: ConfigMap
    name: ingress-input
    apiVersion: v1
  fieldref:
    fieldpath: data.INGRESS_HOST