kind: Component

transformers:
- sas-analytics-events-transformers.yaml
- sas-analytics-execution-transformers.yaml
- sas-analytics-gateway-transformers.yaml
- sas-analytics-resources-transformers.yaml
- sas-annotations-transformers.yaml
- sas-app-registry-transformers.yaml
- sas-audit-transformers.yaml
- sas-authorization-transformers.yaml
- sas-batch-transformers.yaml
- sas-cas-control-transformers.yaml
- sas-catalog-services-transformers.yaml
- sas-code-debugger-transformers.yaml
- sas-code-debugger-app-transformers.yaml
- sas-collaboration-transformers.yaml
- sas-compute-transformers.yaml
- sas-configuration-transformers.yaml
- sas-connect-transformers.yaml
- sas-content-transformers.yaml
- sas-credentials-transformers.yaml
- sas-data-agent-server-colocated-transformers.yaml
- sas-data-agent-services-transformers.yaml
- sas-data-explorer-app-transformers.yaml
- sas-data-flows-transformers.yaml
- sas-data-mining-project-resources-transformers.yaml
- sas-data-mining-results-transformers.yaml
- sas-data-mining-risk-models-transformers.yaml
- sas-data-quality-services-transformers.yaml
- sas-data-sources-transformers.yaml
- sas-decision-manager-app-transformers.yaml
- sas-decisions-framework-transformers.yaml
- sas-decisions-runtime-builder-transformers.yaml
- sas-deployment-data-transformers.yaml
- sas-device-management-transformers.yaml
- sas-drive-app-transformers.yaml
- sas-environment-manager-app-transformers.yaml
- sas-file-store-transformers.yaml
- sas-files-transformers.yaml
- sas-formats-transformers.yaml
- sas-gen-ai-gateway-transformers.yaml
- sas-geography-transformers.yaml
- sas-graph-builder-app-transformers.yaml
- sas-graph-templates-transformers.yaml
- sas-identities-transformers.yaml
- sas-import-9-transformers.yaml
- sas-information-catalog-app-transformers.yaml
- sas-insights-transformers.yaml
- sas-job-execution-transformers.yaml
- sas-job-execution-app-transformers.yaml
- sas-job-flow-scheduling-transformers.yaml
- sas-landing-app-transformers.yaml
- sas-launcher-transformers.yaml
- sas-lineage-app-transformers.yaml
- sas-list-data-transformers.yaml
- sas-localization-transformers.yaml
- sas-logon-app-transformers.yaml
- sas-microanalytic-score-transformers.yaml
- sas-migration-manager-transformers.yaml
- sas-ml-pipeline-automation-transformers.yaml
- sas-model-manager-transformers.yaml
- sas-model-manager-app-transformers.yaml
- sas-model-publish-transformers.yaml
- sas-model-studio-app-transformers.yaml
- sas-natural-language-generation-transformers.yaml
- sas-office-addin-app-transformers.yaml
- sas-preferences-transformers.yaml
- sas-report-alerts-transformers.yaml
- sas-report-distribution-transformers.yaml
- sas-report-execution-transformers.yaml
- sas-report-renderers-transformers.yaml
- sas-report-services-group-transformers.yaml
- sas-risk-cirrus-app-transformers.yaml
- sas-risk-cirrus-builder-transformers.yaml
- sas-risk-cirrus-core-transformers.yaml
- sas-risk-cirrus-objects-transformers.yaml
- sas-risk-data-transformers.yaml
- sas-risk-modeling-app-transformers.yaml
- sas-risk-modeling-core-transformers.yaml
- sas-scheduler-transformers.yaml
- sas-score-definitions-transformers.yaml
- sas-score-execution-transformers.yaml
- sas-search-transformers.yaml
- sas-studio-transformers.yaml
- sas-studio-app-transformers.yaml
- sas-studio-development-transformers.yaml
- sas-subject-contacts-transformers.yaml
- sas-text-analytics-data-transformers.yaml
- sas-text-analytics-taxonomies-transformers.yaml
- sas-theme-designer-app-transformers.yaml
- sas-transfer-transformers.yaml
- sas-treatment-definitions-transformers.yaml
- sas-visual-analytics-transformers.yaml
- sas-visual-analytics-app-transformers.yaml
- sas-web-assets-transformers.yaml
- sas-webhooks-transformers.yaml
- sas-workflow-engine-transformers.yaml
- sas-workflow-history-transformers.yaml
- sas-workflow-manager-app-transformers.yaml
- sas-workload-orchestrator-transformers.yaml
