---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-config-reconciler-route-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: replace
    path: /spec/tls
    value:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  - op: add
    path: /metadata/annotations/cert-utils-operator.redhat-cop.io~1certs-from-secret
    value: sas-ingress-certificate
target:
  kind: Route
  group: route.openshift.io
  version: v1
  name: sas-config-reconciler
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-config-reconciler-multitenant-route-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: replace
    path: /spec/tls
    value:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  - op: add
    path: /metadata/annotations/cert-utils-operator.redhat-cop.io~1certs-from-secret
    value: sas-ingress-certificate
target:
  kind: Route
  group: route.openshift.io
  version: v1
  name: sas-config-reconciler-multitenant
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-configuration-route-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: replace
    path: /spec/tls
    value:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  - op: add
    path: /metadata/annotations/cert-utils-operator.redhat-cop.io~1certs-from-secret
    value: sas-ingress-certificate
target:
  kind: Route
  group: route.openshift.io
  version: v1
  name: sas-configuration
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-configuration-multitenant-route-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: replace
    path: /spec/tls
    value:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  - op: add
    path: /metadata/annotations/cert-utils-operator.redhat-cop.io~1certs-from-secret
    value: sas-ingress-certificate
target:
  kind: Route
  group: route.openshift.io
  version: v1
  name: sas-configuration-multitenant
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-feature-flags-route-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: replace
    path: /spec/tls
    value:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  - op: add
    path: /metadata/annotations/cert-utils-operator.redhat-cop.io~1certs-from-secret
    value: sas-ingress-certificate
target:
  kind: Route
  group: route.openshift.io
  version: v1
  name: sas-feature-flags
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-feature-flags-multitenant-route-front-door-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: front-door
  - op: replace
    path: /spec/tls
    value:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  - op: add
    path: /metadata/annotations/cert-utils-operator.redhat-cop.io~1certs-from-secret
    value: sas-ingress-certificate
target:
  kind: Route
  group: route.openshift.io
  version: v1
  name: sas-feature-flags-multitenant
