---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-config-reconciler-httpproxy-full-stack-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /spec/routes/0/services/0/protocol
    value: tls
  - op: replace
    path: /spec/routes/0/services/0/port
    value: 443
  - op: add
    path: /spec/routes/1/services/0/protocol
    value: tls
  - op: replace
    path: /spec/routes/1/services/0/port
    value: 443
target:
  kind: HTTPProxy
  group: projectcontour.io
  version: v1
  name: sas-config-reconciler
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-configuration-httpproxy-full-stack-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /spec/routes/0/services/0/protocol
    value: tls
  - op: replace
    path: /spec/routes/0/services/0/port
    value: 443
  - op: add
    path: /spec/routes/1/services/0/protocol
    value: tls
  - op: replace
    path: /spec/routes/1/services/0/port
    value: 443
target:
  kind: HTTPProxy
  group: projectcontour.io
  version: v1
  name: sas-configuration
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-feature-flags-httpproxy-full-stack-tls-transformer
patch: |-
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /spec/routes/0/services/0/protocol
    value: tls
  - op: replace
    path: /spec/routes/0/services/0/port
    value: 443
  - op: add
    path: /spec/routes/1/services/0/protocol
    value: tls
  - op: replace
    path: /spec/routes/1/services/0/port
    value: 443
target:
  kind: HTTPProxy
  group: projectcontour.io
  version: v1
  name: sas-feature-flags
