nameReference:
- kind: ClusterRoleBinding
  version: rbac.authorization.k8s.io/v1
  fieldSpecs:
  - path: subjects/namespace
    kind: ClusterRoleBinding
varReference:
  - path: roleRef/name
    kind: ClusterRoleBinding
  - path: subjects/name
    kind: ClusterRoleBinding
  - path: metadata/name
    kind: ClusterRoleBinding