apiVersion: orchestration.sas.com/v2beta6
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-pyconfig
    sas.com/component-version: 1.30.56-20251014.1760453664787
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-pyconfig
  name: deploy-pre-pyconfig-execute
spec:
  args:
  - name: namespace
  - name: timeout
  steps:
  - args:
    - delete
    - --namespace
    - $namespace
    - --wait
    - --timeout
    - $timeout
    - --ignore-not-found
    - job
    - sas-pyconfig-cjinitial
    cmd: kubectl
  - args:
    - delete
    - --namespace
    - $namespace
    - --wait
    - --timeout
    - $timeout
    - --ignore-not-found
    - job
    - sas-pyconfig
    cmd: kubectl
  - args:
    - delete
    - --namespace
    - $namespace
    - --wait
    - --timeout
    - $timeout
    - --ignore-not-found
    - job
    - sas-pyconfig-job
    cmd: kubectl
