apiVersion: orchestration.sas.com/v2beta6
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-pyconfig
    sas.com/component-version: 1.30.56-20251014.1760453664787
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-pyconfig
    participate.lifecycle.sas.com/deploy-pre: "true"
  name: deploy-pre-pyconfig
spec:
  args:
  - name: namespace
  - name: timeout
  steps:
  - args:
    - deploy-pre-pyconfig-execute
    - --namespace
    - $namespace
    - --timeout
    - $timeout
    cmd: run
    when: |-
      (eq
        "true"
        (.Annotation "sas.com/sas-pyconfig-update" (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithNamespace $namespace).WithGroup "").WithVersion "v1").WithResource "configmap").WithName "sas-deploy-lifecycle-operation-variables")))
      )
