apiVersion: orchestration.sas.com/v2beta6
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-pyconfig
    sas.com/component-version: 1.30.56-20251014.1760453664787
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-pyconfig
  name: pyconfig-runonce-execute
spec:
  args:
  - name: namespace
    require: true
  steps:
  - args:
    - create
    - job
    - --namespace
    - $namespace
    - --from
    - cronjob/sas-pyconfig
    - sas-pyconfig-cjinitial
    cmd: kubectl
