kind: Component
images:
- name: image-pgadmin
  newName: registry.crunchydata.com/crunchydata/crunchy-pgadmin4
  newTag: ubi8-9.2-2516
- name: image-pgadmin-v4
  newName: registry.crunchydata.com/crunchydata/crunchy-pgadmin4
  newTag: ubi8-4.30-2516
- name: image-pgbackrest
  newName: registry.crunchydata.com/crunchydata/crunchy-pgbackrest
  newTag: ubi8-2.54.2-2516
- name: image-pgbouncer
  newName: registry.crunchydata.com/crunchydata/crunchy-pgbouncer
  newTag: ubi8-1.24-2516
- name: image-postgres-exporter
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-exporter
  newTag: ubi8-0.17.1-2516
- name: image-postgres-operator-5.7
  newName: registry.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.7.5-0
- name: image-postgres-operator-5.6
  newName: registry.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.6.7-0
- name: image-postgres-operator-5.5
  newName: registry.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.5.9-0
- name: image-crunchy-postgres-13
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi8-13.20-2516
- name: image-crunchy-postgres-14
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi8-14.17-2516
- name: image-crunchy-postgres-15
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi8-15.12-2516
- name: image-crunchy-postgres-16
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi8-16.8-2516
- name: image-crunchy-postgres-17
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres
  newTag: ubi8-17.4-2516
- name: image-crunchy-postgres-13-citus-11.3
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-citus
  newTag: ubi8-13.20-11.3.1-2516
- name: image-crunchy-postgres-14-citus-13.0
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-citus
  newTag: ubi8-14.17-13.0.0-2516
- name: image-crunchy-postgres-15-citus-13.0
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-citus
  newTag: ubi8-15.12-13.0.0-2516
- name: image-crunchy-postgres-16-citus-13.0
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-citus
  newTag: ubi8-16.8-13.0.0-2516
- name: image-crunchy-postgres-17-citus-13.0
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-citus
  newTag: ubi8-17.4-13.0.0-2516
- name: image-crunchy-upgrade
  newName: registry.crunchydata.com/crunchydata/crunchy-upgrade
  newTag: ubi8-17.4-2516
- name: image-crunchy-postgres-13-gis-3.0
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-13.20-3.0-2516
- name: image-crunchy-postgres-13-gis-3.1
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-13.20-3.1-2516
- name: image-crunchy-postgres-14-gis-3.1
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-14.17-3.1-2516
- name: image-crunchy-postgres-14-gis-3.2
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-14.17-3.2-2516
- name: image-crunchy-postgres-14-gis-3.3
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-14.17-3.3-2516
- name: image-crunchy-postgres-15-gis-3.3
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-15.12-3.3-2516
- name: image-crunchy-postgres-16-gis-3.3
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-16.8-3.3-2516
- name: image-crunchy-postgres-16-gis-3.4
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-16.8-3.4-2516
- name: image-crunchy-postgres-17-gis-3.4
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-17.4-3.4-2516
- name: image-crunchy-postgres-17-gis-3.5
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-gis
  newTag: ubi8-17.4-3.5-2516
- name: image-crunchy-postgres-15-plv8
  newName: registry.crunchydata.com/crunchydata/crunchy-postgres-plv8
  newTag: ubi8-15.12-3.2.3-2516
- name: image-stig-playbook
  newName: registry.crunchydata.com/crunchydata-stig/crunchy-postgres-stig-playbook
  newTag: ubi8-1.0.2-2516
