apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-deployment-buildinfo
data:
  git-hash: "03f6063f13d60ab96d4b6da527cbae8729f00c56"
  timestamp: "2025-11-28T22:11:09Z"
  deployment-tooling: "ansible"