apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-deployment-buildinfo
data:
  git-hash: "b8e7a5641b4daf403dca8087a08e404f45127cb1"
  timestamp: "2025-11-25T15:55:16Z"
  deployment-tooling: "ansible"