apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-deployment-buildinfo
data:
  git-hash: "78aa52335a9533972f431774c5a30c02d0d4ae6a"
  timestamp: "2025-11-26T01:55:19Z"
  deployment-tooling: "ansible"