apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: sas-kerberos-config
literals:
  - SPRING_PROFILES_ACTIVE=ldap,postgresql,kerberos
  - JAVA_OPTION_KRB5_CONF=-Djava.security.krb5.conf=/opt/kerberos/krb5.conf
  - SAS_LOGON_KERBEROS_KEYTABLOCATION=file:///opt/kerberos/keytab
  - JAVA_OPTION_KRB5_DEBUG=-Dsun.security.krb5.debug=false
  - JAVA_OPTION_JGSS_DEBUG=-Dsun.security.jgss.debug=false
  - SAS_LOGON_KERBEROS_DEBUG=true
  - SAS_LOGON_KERBEROS_DISABLEDELEGATIONWARNING=true
  - SAS_LOGON_KERBEROS_HOLDONTOGSSCONTEXT=false