apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-oracle-env-to-deployment
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/envFrom/-
    value:
      secretRef:
        name: oracle-credentials
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DATABASE_DRIVER_OVERRIDE_EXPERIMENTAL
      value: "oracle"
target:
  kind: Deployment
  name: sas-data-server-operator
---
